# Generated by Django 2.2.2 on 2019-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_prodottoordinato_id_tavolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottoordinato',
            name='id_tavolo',
            field=models.PositiveSmallIntegerField(default=131),
            preserve_default=False,
        ),
    ]
