# Generated by Django 2.2.2 on 2019-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190623_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='tempo_preparazione',
            field=models.PositiveIntegerField(),
        ),
    ]
