# Generated by Django 2.2.2 on 2019-06-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190623_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodotto',
            old_name='tempo_preparazione',
            new_name='tempoPreparazione',
        ),
        migrations.RenameField(
            model_name='prodotto',
            old_name='tipo_prodotto',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='prodotto',
            old_name='tipo_portata',
            new_name='tipoPortata',
        ),
    ]
