# Generated by Django 2.2.2 on 2019-07-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190625_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AlterModelOptions(
            name='prodottoordinato',
            options={'verbose_name_plural': 'Prodotti Ordinati'},
        ),
    ]
