# Generated by Django 2.2.2 on 2019-06-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodottoordinato',
            old_name='tempo_inizio_lavorazione',
            new_name='tempoInizioLavorazione',
        ),
    ]
