# Generated by Django 2.2.2 on 2019-06-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190618_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodottoordinato',
            name='id_tavolo',
        ),
    ]
