# Generated by Django 2.2.2 on 2019-06-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_prodottoordinato_id_tavolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodottoordinato',
            old_name='stato_prodotto_ordinato',
            new_name='statoProdottoOrdinato',
        ),
    ]
