# Generated by Django 2.2.2 on 2019-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20190623_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottoordinato',
            name='statoProdottoOrdinato',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ORDINATO'), (1, 'LAVORAZIONE'), (2, 'CONSEGNATO')], default=1),
        ),
    ]
