# Generated by Django 2.2.2 on 2019-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190625_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'CUCINA'), (1, 'CAFFETTERIA')]),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='tipoPortata',
            field=models.SmallIntegerField(choices=[(0, 'PIATTI'), (1, 'BEVANDE'), (2, 'VINI'), (3, 'DOLCI')]),
        ),
        migrations.DeleteModel(
            name='TipoPortata',
        ),
        migrations.DeleteModel(
            name='TipoProdotto',
        ),
    ]
